---
- name: Copy conductr agent deb package
  copy:
    dest: /tmp/conductr-agent.deb
    src: "conductr-agent_{{ conductr_agent.version }}.deb"

- name: Install conductr agent
  become: true
  apt:
    deb: /tmp/conductr-agent.deb
    state: present

- name: Set config for conductr-agent
  become: true
  template:
      dest: /usr/share/conductr-agent/conf/conductr-agent.ini
      src: conductr-agent.ini.j2
  notify:
    - restart conductr-agent

- name: Let conductr-agent own haproxy conf
  become: true
  file:
    path: /etc/haproxy/haproxy.cfg
    owner: conductr-agent
    group: conductr-agent

- name: Create HAproxy startup script
  become: true
  copy:
    content: ""
    force: false
    mode: 0770
    dest: /usr/bin/reloadHAproxy.sh
    owner: conductr-agent
    group: conductr-agent

- name: Allow 'conductr-agent' to reload HA proxy as passwordless sudo 
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'conductr-agent ALL=(root) NOPASSWD: /usr/bin/reloadHAProxy.sh'
    validate: visudo -cf %s
  notify:
    - restart conductr-agent

- name: Update license
  environment:
    CONDUCTR_HOST: "{{ ansible_default_ipv4.address }}"
  run_once: true
  block:
    - name: Check license
      command: conduct info
      register: conduct_info
      changed_when: false
    - name: Load license
      command: conduct load-license
      args:
        stdin: "{{ conductr_agent.license_key | quote }}"
      when: "conduct_info.stdout_lines[0].split(': ') == 'unknown'"
