plugin: gcp_compute
strict: true
projects:
    - harbinger-212217
filters:
    - labels.environment = stage
groups:
    seeds: labels.conductr == 'seed'
compose:
    env: stage
auth_kind: serviceaccount
service_account_file: ./service_account.json