plugin: gcp_compute
strict: true
projects:
    - harbinger-212217
filters:
    - labels.environment = stage
groups:
    seeds: labels.conductr == 'seed'
compose:
    conductr_core:
        seed: "{{ hostvars[groups['seeds'][0]].networkInterfaces[0].networkIP }}"
auth_kind: serviceaccount
service_account_file: ./service_account.json