---
- hosts: all
  gather_facts: false
  tags:
    - install

  tasks:
    - name: Install python 2
      raw: sudo bash -c "test -e /usr/bin/python || (apt-get -qqy update && apt-get install -qy python-minimal)"
      changed_when: false
