---
- name: Configure conductr cluster
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - java
    - haproxy
    - rsyslog
    - conductr_cli
    - conductr_core
    - conductr_agent
