---
- name: Load license
  command: >
    conduct load-license --host {{ ansible_default_ipv4.address | quote }}
  args:
    stdin: "{{ conductr_license_key | mandatory }}"
  run_once: true

- name: Load haproxy bundle
  command: >
    conduct load --host {{ ansible_default_ipv4.address | quote }} conductr-haproxy
  run_once: true

- name: Run haproxy bundles
  command: >
    conduct run --host {{ ansible_default_ipv4.address | quote }} 
    conductr-haproxy --scale {{ ansible_play_hosts | length }}
  run_once: true
