---
- name: Install JDK
  become: true
  apt:
    name: openjdk-8-jdk
    state: present

- name: Copy conductr core deb package
  copy:
    dest: /tmp/conductr.deb
    src: "conductr_{{ conductr_version }}.deb"

- name: Install conductr core
  become: true
  apt:
    deb: /tmp/conductr.deb
    state: present

- name: Copy conductr agent deb package
  copy:
    dest: /tmp/conductr-agent.deb
    src: "conductr-agent_{{ conductr_version }}.deb"

- name: Install conductr agent
  become: true
  apt:
    deb: /tmp/conductr-agent.deb
    state: present

- name: Ensure rsyslog installed
  become: true
  apt:
    name: rsyslog
    state: present

- name: Install HAproxy on agent
  become: true
  apt:
    name: haproxy
    state: latest

- name: Ensure unzip installed
  become: true
  apt:
    name: unzip
    state: present

- name: Download conductr binaries
  become: true
  unarchive:
    src: https://bintray.com/lightbend/generic/download_file?file_path=conductr-cli-{{ conductr_cli_version }}.zip
    dest: /usr/local/bin
    remote_src: true
